version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # Cambiamos el empty password de yes a No, para ponerle nuestra contrase単a personalizada
      - ALLOW_EMPTY_PASSWORD=yes
      # Establecemos el usuario personalizado
      - MARIADB_USER=pepe
      # Establecemos el nombre de la base de datos peersonalizada.
      - MARIADB_DATABASE=miTienda
      # Establecemos la contrase単a personalizada
      - MARIADB_PASSWORD=pepe
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:8
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      # A単adimos las variables de usuario y contrase単as iguales que las de Maria db 
      # Pero en el containter de prestashop.
      - PRESTASHOP_DATABASE_USER=pepe
      - PRESTASHOP_DATABASE_PASSWORD=pepe
      - PRESTASHOP_DATABASE_NAME=miTienda
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
